name: Deploy to sffnoobs environment on push to Triondev

on:
  push:
    branches: [ Triondev ]
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-sffnoobs-environment:
    runs-on: ubuntu-latest
    environment: newwnvi

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Install sfdx git delta
        run: |
          echo Y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: Create delta packages
        run: |
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/
          echo "[INFO] Diff generated"

      - name: Deploy to environment with all local tests
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt \
            --username "${{ secrets.DEPLOYMENT_USERNAME }}" \
            --jwt-key-file server.key \
            --client-id "${{ secrets.CONSUMER_KEY }}" \
            --instance-url "${{ vars.INSTANCE_URL }}" \
            --set-default
          
          sf project deploy start \
            --source-dir changed-sources/force-app \
            --test-level RunLocalTests
