name: Salesforce CD Pipeline

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  sync-salesforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate to Salesforce using JWT
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant \
            --clientid ${{ secrets.SF_CLIENT_ID }} \
            --jwtkeyfile server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --setalias sf-org \
            --instanceurl https://login.salesforce.com
      - name: Retrieve Apex Classes from Salesforce
        run: sfdx force:source:retrieve -m ApexClass -u sf-org

      - name: Commit and push changes to GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Sync from Salesforce org"
            git push
          fi
